### PR TITLE
docs(readme): fix description to 2.0.0

### PR DESCRIPTION
**Pull request by ya-woodcutter**

### CODE REVIEW

**Comment by ya-woodcutter** [comment]
REVIEW: @Blackheart340 @evilj0e

**Comment by TimeRaider** [comment]
@ya-woodcutter it's unclear whether `cache[method](store, key, value)` is asynchronous or not

**Comment by TimeRaider** [comment]
addresses #9

**Comment by ya-woodcutter** [comment]
@TimeRaider 🆙

**Review by TimeRaider — APPROVED** [review]

**Review by Blackheart340 — APPROVED** [review]

**Pull request merged**
